### ISSUE TITLE
crash when opening options screen with vulkanmod

### ISSUE THREAD

**Issue by uku3lig** [uku3lig/ukulib#12]
issue comes from rendering `IconButton`, when calling `DrawContext#drawTexture` (`method_25291`)

affected versions: >1.0.0

stacktrace:
```
java.lang.NullPointerException: Cannot invoke "net.vulkanmod.vulkan.texture.VulkanImage.getTextureSampler()" because the return value of "net.vulkanmod.vulkan.texture.VTextureSelector.getTexture(String)" is null
	at net.vulkanmod.vulkan.shader.Pipeline$DescriptorSets.updateDescriptorSet(Pipeline.java:269)
	at net.vulkanmod.vulkan.shader.Pipeline$DescriptorSets.bindSets(Pipeline.java:233)
	at net.vulkanmod.vulkan.shader.Pipeline.bindDescriptorSets(Pipeline.java:182)
	at net.vulkanmod.vulkan.Renderer.uploadAndBindUBOs(Renderer.java:450)
	at net.minecraft.class_286.method_43433(class_286.java:539)
	at net.minecraft.class_332.method_25295(class_332.java:453)
	at net.minecraft.class_332.method_25297(class_332.java:433)
	at net.minecraft.class_332.method_25291(class_332.java:405)
	at net.uku3lig.ukulib.utils.IconButton.method_48579(IconButton.java:124)
	at net.minecraft.class_339.method_25394(class_339.java:73)
	at net.minecraft.class_437.method_25394(class_437.java:121)
	at net.minecraft.class_429.method_25394(class_429.java:147)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

**Comment by uku3lig** [comment]
crash is caused by the textures not being registered properly in vulkanmod for some unknown reason
